name: gameleven
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: {sdk: '>=2.18.0 <3.0.0'}
dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_slidable: ^1.2.0
  flutter_carousel_slider: ^1.0.8
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  rotated_corner_decoration: ^2.0.0
  carousel_slider: ^4.1.1
  introduction_screen: ^3.0.2
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  hexcolor: any
  get_storage: any
  flutter_widget_from_html: ^0.9.0+1
  flutter_staggered_grid_view: ^0.4.0
  connectivity_plus:
  shared_value: ^2.1.0
  shimmer: ^2.0.0
  progress_dialog_null_safe: ^1.0.7
  flutter_rating_bar: ^4.0.1
  coupon_uikit: ^0.1.0


  http: ^0.13.5
  intl: ^0.17.0
  flutter: {sdk: flutter}
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: {sdk: flutter}
flutter:
  uses-material-design: true
  assets:
    -  assets/
    -  assets/language_flag/
